name: Build and Push Docker Image to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables
      id: set-env
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV
        echo "AWS_REGION=${{ secrets.AWS_REGION_ECR }}" >> $GITHUB_ENV
        echo "AWS_ECR=${{ secrets.AWS_ECR }}" >> $GITHUB_ENV
        echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> $GITHUB_ENV
        echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "FRONT_URL=${{ vars.FRONT_URL }}" >> $GITHUB_ENV

    - name: Debug Environment Variables
      run: |
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
        echo "AWS_REGION: $AWS_REGION"
        echo "AWS_ECR: $AWS_ECR"
        echo "AWS_S3_BUCKET_NAME: $AWS_S3_BUCKET_NAME"
        echo "DATABASE_URL: $DATABASE_URL"
        echo "DATABASE_NAME: $DATABASE_NAME"
        echo "FRONT_URL: $FRONT_URL"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up AWS ECR credentials
      uses: aws-actions/amazon-ecr-login@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION_ECR }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_ECR }}.amazonaws.com/${{ secrets.AWS_ECR }}:latest .

    - name: Push Docker image to AWS ECR
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION_ECR }}.amazonaws.com/${{ secrets.AWS_ECR }}:latest
