name: format

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --no-root
    - name: Run black check
      run: poetry run black --check --diff .
  isort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --no-root
    - name: Run isort check
      run: poetry run isort --check-only --diff .
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --no-root
    - name: Run flake8 check
      run: poetry run flake8 --count .
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: 'pyproject.toml'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --no-root
    - name: Run mypy check
      run: poetry run mypy .
